# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import fileservice_pb2 as fileservice__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in fileservice_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FileServiceStub:
    """File service for virtual filesystem operations
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.MakeDirectory = channel.unary_unary(
                '/fileengine.FileService/MakeDirectory',
                request_serializer=fileservice__pb2.MakeDirectoryRequest.SerializeToString,
                response_deserializer=fileservice__pb2.MakeDirectoryResponse.FromString,
                _registered_method=True)
        self.RemoveDirectory = channel.unary_unary(
                '/fileengine.FileService/RemoveDirectory',
                request_serializer=fileservice__pb2.RemoveDirectoryRequest.SerializeToString,
                response_deserializer=fileservice__pb2.RemoveDirectoryResponse.FromString,
                _registered_method=True)
        self.ListDirectory = channel.unary_unary(
                '/fileengine.FileService/ListDirectory',
                request_serializer=fileservice__pb2.ListDirectoryRequest.SerializeToString,
                response_deserializer=fileservice__pb2.ListDirectoryResponse.FromString,
                _registered_method=True)
        self.CreateFile = channel.unary_unary(
                '/fileengine.FileService/CreateFile',
                request_serializer=fileservice__pb2.CreateFileRequest.SerializeToString,
                response_deserializer=fileservice__pb2.CreateFileResponse.FromString,
                _registered_method=True)
        self.DeleteFile = channel.unary_unary(
                '/fileengine.FileService/DeleteFile',
                request_serializer=fileservice__pb2.DeleteFileRequest.SerializeToString,
                response_deserializer=fileservice__pb2.DeleteFileResponse.FromString,
                _registered_method=True)
        self.UndeleteFile = channel.unary_unary(
                '/fileengine.FileService/UndeleteFile',
                request_serializer=fileservice__pb2.UndeleteFileRequest.SerializeToString,
                response_deserializer=fileservice__pb2.UndeleteFileResponse.FromString,
                _registered_method=True)
        self.WriteFile = channel.unary_unary(
                '/fileengine.FileService/WriteFile',
                request_serializer=fileservice__pb2.WriteFileRequest.SerializeToString,
                response_deserializer=fileservice__pb2.WriteFileResponse.FromString,
                _registered_method=True)
        self.ReadFile = channel.unary_unary(
                '/fileengine.FileService/ReadFile',
                request_serializer=fileservice__pb2.ReadFileRequest.SerializeToString,
                response_deserializer=fileservice__pb2.ReadFileResponse.FromString,
                _registered_method=True)
        self.GetFileInfo = channel.unary_unary(
                '/fileengine.FileService/GetFileInfo',
                request_serializer=fileservice__pb2.GetFileInfoRequest.SerializeToString,
                response_deserializer=fileservice__pb2.GetFileInfoResponse.FromString,
                _registered_method=True)
        self.FileExists = channel.unary_unary(
                '/fileengine.FileService/FileExists',
                request_serializer=fileservice__pb2.FileExistsRequest.SerializeToString,
                response_deserializer=fileservice__pb2.FileExistsResponse.FromString,
                _registered_method=True)
        self.MoveFile = channel.unary_unary(
                '/fileengine.FileService/MoveFile',
                request_serializer=fileservice__pb2.MoveFileRequest.SerializeToString,
                response_deserializer=fileservice__pb2.MoveFileResponse.FromString,
                _registered_method=True)
        self.CopyFile = channel.unary_unary(
                '/fileengine.FileService/CopyFile',
                request_serializer=fileservice__pb2.CopyFileRequest.SerializeToString,
                response_deserializer=fileservice__pb2.CopyFileResponse.FromString,
                _registered_method=True)
        self.RenameFile = channel.unary_unary(
                '/fileengine.FileService/RenameFile',
                request_serializer=fileservice__pb2.RenameFileRequest.SerializeToString,
                response_deserializer=fileservice__pb2.RenameFileResponse.FromString,
                _registered_method=True)
        self.ListVersions = channel.unary_unary(
                '/fileengine.FileService/ListVersions',
                request_serializer=fileservice__pb2.ListVersionsRequest.SerializeToString,
                response_deserializer=fileservice__pb2.ListVersionsResponse.FromString,
                _registered_method=True)
        self.ReadVersion = channel.unary_unary(
                '/fileengine.FileService/ReadVersion',
                request_serializer=fileservice__pb2.ReadVersionRequest.SerializeToString,
                response_deserializer=fileservice__pb2.ReadVersionResponse.FromString,
                _registered_method=True)
        self.SetMetadata = channel.unary_unary(
                '/fileengine.FileService/SetMetadata',
                request_serializer=fileservice__pb2.SetMetadataRequest.SerializeToString,
                response_deserializer=fileservice__pb2.SetMetadataResponse.FromString,
                _registered_method=True)
        self.GetMetadata = channel.unary_unary(
                '/fileengine.FileService/GetMetadata',
                request_serializer=fileservice__pb2.GetMetadataRequest.SerializeToString,
                response_deserializer=fileservice__pb2.GetMetadataResponse.FromString,
                _registered_method=True)
        self.GetAllMetadata = channel.unary_unary(
                '/fileengine.FileService/GetAllMetadata',
                request_serializer=fileservice__pb2.GetAllMetadataRequest.SerializeToString,
                response_deserializer=fileservice__pb2.GetAllMetadataResponse.FromString,
                _registered_method=True)
        self.DeleteMetadata = channel.unary_unary(
                '/fileengine.FileService/DeleteMetadata',
                request_serializer=fileservice__pb2.DeleteMetadataRequest.SerializeToString,
                response_deserializer=fileservice__pb2.DeleteMetadataResponse.FromString,
                _registered_method=True)
        self.GetMetadataForVersion = channel.unary_unary(
                '/fileengine.FileService/GetMetadataForVersion',
                request_serializer=fileservice__pb2.GetMetadataForVersionRequest.SerializeToString,
                response_deserializer=fileservice__pb2.GetMetadataForVersionResponse.FromString,
                _registered_method=True)
        self.GetAllMetadataForVersion = channel.unary_unary(
                '/fileengine.FileService/GetAllMetadataForVersion',
                request_serializer=fileservice__pb2.GetAllMetadataForVersionRequest.SerializeToString,
                response_deserializer=fileservice__pb2.GetAllMetadataForVersionResponse.FromString,
                _registered_method=True)
        self.WriteFileStream = channel.stream_unary(
                '/fileengine.FileService/WriteFileStream',
                request_serializer=fileservice__pb2.WriteFileStreamRequest.SerializeToString,
                response_deserializer=fileservice__pb2.WriteFileStreamResponse.FromString,
                _registered_method=True)
        self.ReadFileStream = channel.unary_stream(
                '/fileengine.FileService/ReadFileStream',
                request_serializer=fileservice__pb2.ReadFileStreamRequest.SerializeToString,
                response_deserializer=fileservice__pb2.ReadFileStreamResponse.FromString,
                _registered_method=True)
        self.ResolvePath = channel.unary_unary(
                '/fileengine.FileService/ResolvePath',
                request_serializer=fileservice__pb2.ResolvePathRequest.SerializeToString,
                response_deserializer=fileservice__pb2.ResolvePathResponse.FromString,
                _registered_method=True)
        self.EvaluateACL = channel.unary_unary(
                '/fileengine.FileService/EvaluateACL',
                request_serializer=fileservice__pb2.EvaluateACLRequest.SerializeToString,
                response_deserializer=fileservice__pb2.EvaluateACLResponse.FromString,
                _registered_method=True)


class FileServiceServicer:
    """File service for virtual filesystem operations
    """

    def MakeDirectory(self, request, context):
        """Directory operations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveDirectory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListDirectory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateFile(self, request, context):
        """File operations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UndeleteFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WriteFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFileInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FileExists(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MoveFile(self, request, context):
        """File manipulation
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CopyFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RenameFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListVersions(self, request, context):
        """Version control
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadVersion(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetMetadata(self, request, context):
        """Metadata operations (versioned)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMetadata(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAllMetadata(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteMetadata(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMetadataForVersion(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAllMetadataForVersion(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WriteFileStream(self, request_iterator, context):
        """Streaming operations for large files
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadFileStream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResolvePath(self, request, context):
        """Path resolution operations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EvaluateACL(self, request, context):
        """ACL operations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FileServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'MakeDirectory': grpc.unary_unary_rpc_method_handler(
                    servicer.MakeDirectory,
                    request_deserializer=fileservice__pb2.MakeDirectoryRequest.FromString,
                    response_serializer=fileservice__pb2.MakeDirectoryResponse.SerializeToString,
            ),
            'RemoveDirectory': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveDirectory,
                    request_deserializer=fileservice__pb2.RemoveDirectoryRequest.FromString,
                    response_serializer=fileservice__pb2.RemoveDirectoryResponse.SerializeToString,
            ),
            'ListDirectory': grpc.unary_unary_rpc_method_handler(
                    servicer.ListDirectory,
                    request_deserializer=fileservice__pb2.ListDirectoryRequest.FromString,
                    response_serializer=fileservice__pb2.ListDirectoryResponse.SerializeToString,
            ),
            'CreateFile': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateFile,
                    request_deserializer=fileservice__pb2.CreateFileRequest.FromString,
                    response_serializer=fileservice__pb2.CreateFileResponse.SerializeToString,
            ),
            'DeleteFile': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteFile,
                    request_deserializer=fileservice__pb2.DeleteFileRequest.FromString,
                    response_serializer=fileservice__pb2.DeleteFileResponse.SerializeToString,
            ),
            'UndeleteFile': grpc.unary_unary_rpc_method_handler(
                    servicer.UndeleteFile,
                    request_deserializer=fileservice__pb2.UndeleteFileRequest.FromString,
                    response_serializer=fileservice__pb2.UndeleteFileResponse.SerializeToString,
            ),
            'WriteFile': grpc.unary_unary_rpc_method_handler(
                    servicer.WriteFile,
                    request_deserializer=fileservice__pb2.WriteFileRequest.FromString,
                    response_serializer=fileservice__pb2.WriteFileResponse.SerializeToString,
            ),
            'ReadFile': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadFile,
                    request_deserializer=fileservice__pb2.ReadFileRequest.FromString,
                    response_serializer=fileservice__pb2.ReadFileResponse.SerializeToString,
            ),
            'GetFileInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFileInfo,
                    request_deserializer=fileservice__pb2.GetFileInfoRequest.FromString,
                    response_serializer=fileservice__pb2.GetFileInfoResponse.SerializeToString,
            ),
            'FileExists': grpc.unary_unary_rpc_method_handler(
                    servicer.FileExists,
                    request_deserializer=fileservice__pb2.FileExistsRequest.FromString,
                    response_serializer=fileservice__pb2.FileExistsResponse.SerializeToString,
            ),
            'MoveFile': grpc.unary_unary_rpc_method_handler(
                    servicer.MoveFile,
                    request_deserializer=fileservice__pb2.MoveFileRequest.FromString,
                    response_serializer=fileservice__pb2.MoveFileResponse.SerializeToString,
            ),
            'CopyFile': grpc.unary_unary_rpc_method_handler(
                    servicer.CopyFile,
                    request_deserializer=fileservice__pb2.CopyFileRequest.FromString,
                    response_serializer=fileservice__pb2.CopyFileResponse.SerializeToString,
            ),
            'RenameFile': grpc.unary_unary_rpc_method_handler(
                    servicer.RenameFile,
                    request_deserializer=fileservice__pb2.RenameFileRequest.FromString,
                    response_serializer=fileservice__pb2.RenameFileResponse.SerializeToString,
            ),
            'ListVersions': grpc.unary_unary_rpc_method_handler(
                    servicer.ListVersions,
                    request_deserializer=fileservice__pb2.ListVersionsRequest.FromString,
                    response_serializer=fileservice__pb2.ListVersionsResponse.SerializeToString,
            ),
            'ReadVersion': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadVersion,
                    request_deserializer=fileservice__pb2.ReadVersionRequest.FromString,
                    response_serializer=fileservice__pb2.ReadVersionResponse.SerializeToString,
            ),
            'SetMetadata': grpc.unary_unary_rpc_method_handler(
                    servicer.SetMetadata,
                    request_deserializer=fileservice__pb2.SetMetadataRequest.FromString,
                    response_serializer=fileservice__pb2.SetMetadataResponse.SerializeToString,
            ),
            'GetMetadata': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMetadata,
                    request_deserializer=fileservice__pb2.GetMetadataRequest.FromString,
                    response_serializer=fileservice__pb2.GetMetadataResponse.SerializeToString,
            ),
            'GetAllMetadata': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAllMetadata,
                    request_deserializer=fileservice__pb2.GetAllMetadataRequest.FromString,
                    response_serializer=fileservice__pb2.GetAllMetadataResponse.SerializeToString,
            ),
            'DeleteMetadata': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteMetadata,
                    request_deserializer=fileservice__pb2.DeleteMetadataRequest.FromString,
                    response_serializer=fileservice__pb2.DeleteMetadataResponse.SerializeToString,
            ),
            'GetMetadataForVersion': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMetadataForVersion,
                    request_deserializer=fileservice__pb2.GetMetadataForVersionRequest.FromString,
                    response_serializer=fileservice__pb2.GetMetadataForVersionResponse.SerializeToString,
            ),
            'GetAllMetadataForVersion': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAllMetadataForVersion,
                    request_deserializer=fileservice__pb2.GetAllMetadataForVersionRequest.FromString,
                    response_serializer=fileservice__pb2.GetAllMetadataForVersionResponse.SerializeToString,
            ),
            'WriteFileStream': grpc.stream_unary_rpc_method_handler(
                    servicer.WriteFileStream,
                    request_deserializer=fileservice__pb2.WriteFileStreamRequest.FromString,
                    response_serializer=fileservice__pb2.WriteFileStreamResponse.SerializeToString,
            ),
            'ReadFileStream': grpc.unary_stream_rpc_method_handler(
                    servicer.ReadFileStream,
                    request_deserializer=fileservice__pb2.ReadFileStreamRequest.FromString,
                    response_serializer=fileservice__pb2.ReadFileStreamResponse.SerializeToString,
            ),
            'ResolvePath': grpc.unary_unary_rpc_method_handler(
                    servicer.ResolvePath,
                    request_deserializer=fileservice__pb2.ResolvePathRequest.FromString,
                    response_serializer=fileservice__pb2.ResolvePathResponse.SerializeToString,
            ),
            'EvaluateACL': grpc.unary_unary_rpc_method_handler(
                    servicer.EvaluateACL,
                    request_deserializer=fileservice__pb2.EvaluateACLRequest.FromString,
                    response_serializer=fileservice__pb2.EvaluateACLResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'fileengine.FileService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('fileengine.FileService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FileService:
    """File service for virtual filesystem operations
    """

    @staticmethod
    def MakeDirectory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fileengine.FileService/MakeDirectory',
            fileservice__pb2.MakeDirectoryRequest.SerializeToString,
            fileservice__pb2.MakeDirectoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveDirectory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fileengine.FileService/RemoveDirectory',
            fileservice__pb2.RemoveDirectoryRequest.SerializeToString,
            fileservice__pb2.RemoveDirectoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListDirectory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fileengine.FileService/ListDirectory',
            fileservice__pb2.ListDirectoryRequest.SerializeToString,
            fileservice__pb2.ListDirectoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fileengine.FileService/CreateFile',
            fileservice__pb2.CreateFileRequest.SerializeToString,
            fileservice__pb2.CreateFileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fileengine.FileService/DeleteFile',
            fileservice__pb2.DeleteFileRequest.SerializeToString,
            fileservice__pb2.DeleteFileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UndeleteFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fileengine.FileService/UndeleteFile',
            fileservice__pb2.UndeleteFileRequest.SerializeToString,
            fileservice__pb2.UndeleteFileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WriteFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fileengine.FileService/WriteFile',
            fileservice__pb2.WriteFileRequest.SerializeToString,
            fileservice__pb2.WriteFileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fileengine.FileService/ReadFile',
            fileservice__pb2.ReadFileRequest.SerializeToString,
            fileservice__pb2.ReadFileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetFileInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fileengine.FileService/GetFileInfo',
            fileservice__pb2.GetFileInfoRequest.SerializeToString,
            fileservice__pb2.GetFileInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FileExists(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fileengine.FileService/FileExists',
            fileservice__pb2.FileExistsRequest.SerializeToString,
            fileservice__pb2.FileExistsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MoveFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fileengine.FileService/MoveFile',
            fileservice__pb2.MoveFileRequest.SerializeToString,
            fileservice__pb2.MoveFileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CopyFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fileengine.FileService/CopyFile',
            fileservice__pb2.CopyFileRequest.SerializeToString,
            fileservice__pb2.CopyFileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RenameFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fileengine.FileService/RenameFile',
            fileservice__pb2.RenameFileRequest.SerializeToString,
            fileservice__pb2.RenameFileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListVersions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fileengine.FileService/ListVersions',
            fileservice__pb2.ListVersionsRequest.SerializeToString,
            fileservice__pb2.ListVersionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadVersion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fileengine.FileService/ReadVersion',
            fileservice__pb2.ReadVersionRequest.SerializeToString,
            fileservice__pb2.ReadVersionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetMetadata(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fileengine.FileService/SetMetadata',
            fileservice__pb2.SetMetadataRequest.SerializeToString,
            fileservice__pb2.SetMetadataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMetadata(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fileengine.FileService/GetMetadata',
            fileservice__pb2.GetMetadataRequest.SerializeToString,
            fileservice__pb2.GetMetadataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAllMetadata(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fileengine.FileService/GetAllMetadata',
            fileservice__pb2.GetAllMetadataRequest.SerializeToString,
            fileservice__pb2.GetAllMetadataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteMetadata(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fileengine.FileService/DeleteMetadata',
            fileservice__pb2.DeleteMetadataRequest.SerializeToString,
            fileservice__pb2.DeleteMetadataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMetadataForVersion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fileengine.FileService/GetMetadataForVersion',
            fileservice__pb2.GetMetadataForVersionRequest.SerializeToString,
            fileservice__pb2.GetMetadataForVersionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAllMetadataForVersion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fileengine.FileService/GetAllMetadataForVersion',
            fileservice__pb2.GetAllMetadataForVersionRequest.SerializeToString,
            fileservice__pb2.GetAllMetadataForVersionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WriteFileStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/fileengine.FileService/WriteFileStream',
            fileservice__pb2.WriteFileStreamRequest.SerializeToString,
            fileservice__pb2.WriteFileStreamResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadFileStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/fileengine.FileService/ReadFileStream',
            fileservice__pb2.ReadFileStreamRequest.SerializeToString,
            fileservice__pb2.ReadFileStreamResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResolvePath(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fileengine.FileService/ResolvePath',
            fileservice__pb2.ResolvePathRequest.SerializeToString,
            fileservice__pb2.ResolvePathResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EvaluateACL(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fileengine.FileService/EvaluateACL',
            fileservice__pb2.EvaluateACLRequest.SerializeToString,
            fileservice__pb2.EvaluateACLResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
