# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import fileservice_pb2 as fileservice__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in fileservice_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FileServiceStub(object):
    """Service definition for the FileEngine virtual filesystem
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.MakeDirectory = channel.unary_unary(
                '/fileengine_rpc.FileService/MakeDirectory',
                request_serializer=fileservice__pb2.MakeDirectoryRequest.SerializeToString,
                response_deserializer=fileservice__pb2.MakeDirectoryResponse.FromString,
                _registered_method=True)
        self.RemoveDirectory = channel.unary_unary(
                '/fileengine_rpc.FileService/RemoveDirectory',
                request_serializer=fileservice__pb2.RemoveDirectoryRequest.SerializeToString,
                response_deserializer=fileservice__pb2.RemoveDirectoryResponse.FromString,
                _registered_method=True)
        self.ListDirectory = channel.unary_unary(
                '/fileengine_rpc.FileService/ListDirectory',
                request_serializer=fileservice__pb2.ListDirectoryRequest.SerializeToString,
                response_deserializer=fileservice__pb2.ListDirectoryResponse.FromString,
                _registered_method=True)
        self.ListDirectoryWithDeleted = channel.unary_unary(
                '/fileengine_rpc.FileService/ListDirectoryWithDeleted',
                request_serializer=fileservice__pb2.ListDirectoryWithDeletedRequest.SerializeToString,
                response_deserializer=fileservice__pb2.ListDirectoryWithDeletedResponse.FromString,
                _registered_method=True)
        self.Touch = channel.unary_unary(
                '/fileengine_rpc.FileService/Touch',
                request_serializer=fileservice__pb2.TouchRequest.SerializeToString,
                response_deserializer=fileservice__pb2.TouchResponse.FromString,
                _registered_method=True)
        self.RemoveFile = channel.unary_unary(
                '/fileengine_rpc.FileService/RemoveFile',
                request_serializer=fileservice__pb2.RemoveFileRequest.SerializeToString,
                response_deserializer=fileservice__pb2.RemoveFileResponse.FromString,
                _registered_method=True)
        self.UndeleteFile = channel.unary_unary(
                '/fileengine_rpc.FileService/UndeleteFile',
                request_serializer=fileservice__pb2.UndeleteFileRequest.SerializeToString,
                response_deserializer=fileservice__pb2.UndeleteFileResponse.FromString,
                _registered_method=True)
        self.PutFile = channel.unary_unary(
                '/fileengine_rpc.FileService/PutFile',
                request_serializer=fileservice__pb2.PutFileRequest.SerializeToString,
                response_deserializer=fileservice__pb2.PutFileResponse.FromString,
                _registered_method=True)
        self.GetFile = channel.unary_unary(
                '/fileengine_rpc.FileService/GetFile',
                request_serializer=fileservice__pb2.GetFileRequest.SerializeToString,
                response_deserializer=fileservice__pb2.GetFileResponse.FromString,
                _registered_method=True)
        self.Stat = channel.unary_unary(
                '/fileengine_rpc.FileService/Stat',
                request_serializer=fileservice__pb2.StatRequest.SerializeToString,
                response_deserializer=fileservice__pb2.StatResponse.FromString,
                _registered_method=True)
        self.Exists = channel.unary_unary(
                '/fileengine_rpc.FileService/Exists',
                request_serializer=fileservice__pb2.ExistsRequest.SerializeToString,
                response_deserializer=fileservice__pb2.ExistsResponse.FromString,
                _registered_method=True)
        self.Rename = channel.unary_unary(
                '/fileengine_rpc.FileService/Rename',
                request_serializer=fileservice__pb2.RenameRequest.SerializeToString,
                response_deserializer=fileservice__pb2.RenameResponse.FromString,
                _registered_method=True)
        self.Move = channel.unary_unary(
                '/fileengine_rpc.FileService/Move',
                request_serializer=fileservice__pb2.MoveRequest.SerializeToString,
                response_deserializer=fileservice__pb2.MoveResponse.FromString,
                _registered_method=True)
        self.Copy = channel.unary_unary(
                '/fileengine_rpc.FileService/Copy',
                request_serializer=fileservice__pb2.CopyRequest.SerializeToString,
                response_deserializer=fileservice__pb2.CopyResponse.FromString,
                _registered_method=True)
        self.ListVersions = channel.unary_unary(
                '/fileengine_rpc.FileService/ListVersions',
                request_serializer=fileservice__pb2.ListVersionsRequest.SerializeToString,
                response_deserializer=fileservice__pb2.ListVersionsResponse.FromString,
                _registered_method=True)
        self.GetVersion = channel.unary_unary(
                '/fileengine_rpc.FileService/GetVersion',
                request_serializer=fileservice__pb2.GetVersionRequest.SerializeToString,
                response_deserializer=fileservice__pb2.GetVersionResponse.FromString,
                _registered_method=True)
        self.RestoreToVersion = channel.unary_unary(
                '/fileengine_rpc.FileService/RestoreToVersion',
                request_serializer=fileservice__pb2.RestoreToVersionRequest.SerializeToString,
                response_deserializer=fileservice__pb2.RestoreToVersionResponse.FromString,
                _registered_method=True)
        self.SetMetadata = channel.unary_unary(
                '/fileengine_rpc.FileService/SetMetadata',
                request_serializer=fileservice__pb2.SetMetadataRequest.SerializeToString,
                response_deserializer=fileservice__pb2.SetMetadataResponse.FromString,
                _registered_method=True)
        self.GetMetadata = channel.unary_unary(
                '/fileengine_rpc.FileService/GetMetadata',
                request_serializer=fileservice__pb2.GetMetadataRequest.SerializeToString,
                response_deserializer=fileservice__pb2.GetMetadataResponse.FromString,
                _registered_method=True)
        self.GetAllMetadata = channel.unary_unary(
                '/fileengine_rpc.FileService/GetAllMetadata',
                request_serializer=fileservice__pb2.GetAllMetadataRequest.SerializeToString,
                response_deserializer=fileservice__pb2.GetAllMetadataResponse.FromString,
                _registered_method=True)
        self.DeleteMetadata = channel.unary_unary(
                '/fileengine_rpc.FileService/DeleteMetadata',
                request_serializer=fileservice__pb2.DeleteMetadataRequest.SerializeToString,
                response_deserializer=fileservice__pb2.DeleteMetadataResponse.FromString,
                _registered_method=True)
        self.GetMetadataForVersion = channel.unary_unary(
                '/fileengine_rpc.FileService/GetMetadataForVersion',
                request_serializer=fileservice__pb2.GetMetadataForVersionRequest.SerializeToString,
                response_deserializer=fileservice__pb2.GetMetadataForVersionResponse.FromString,
                _registered_method=True)
        self.GetAllMetadataForVersion = channel.unary_unary(
                '/fileengine_rpc.FileService/GetAllMetadataForVersion',
                request_serializer=fileservice__pb2.GetAllMetadataForVersionRequest.SerializeToString,
                response_deserializer=fileservice__pb2.GetAllMetadataForVersionResponse.FromString,
                _registered_method=True)
        self.GrantPermission = channel.unary_unary(
                '/fileengine_rpc.FileService/GrantPermission',
                request_serializer=fileservice__pb2.GrantPermissionRequest.SerializeToString,
                response_deserializer=fileservice__pb2.GrantPermissionResponse.FromString,
                _registered_method=True)
        self.RevokePermission = channel.unary_unary(
                '/fileengine_rpc.FileService/RevokePermission',
                request_serializer=fileservice__pb2.RevokePermissionRequest.SerializeToString,
                response_deserializer=fileservice__pb2.RevokePermissionResponse.FromString,
                _registered_method=True)
        self.CheckPermission = channel.unary_unary(
                '/fileengine_rpc.FileService/CheckPermission',
                request_serializer=fileservice__pb2.CheckPermissionRequest.SerializeToString,
                response_deserializer=fileservice__pb2.CheckPermissionResponse.FromString,
                _registered_method=True)
        self.StreamFileUpload = channel.stream_unary(
                '/fileengine_rpc.FileService/StreamFileUpload',
                request_serializer=fileservice__pb2.PutFileRequest.SerializeToString,
                response_deserializer=fileservice__pb2.PutFileResponse.FromString,
                _registered_method=True)
        self.StreamFileDownload = channel.unary_stream(
                '/fileengine_rpc.FileService/StreamFileDownload',
                request_serializer=fileservice__pb2.GetFileRequest.SerializeToString,
                response_deserializer=fileservice__pb2.GetFileResponse.FromString,
                _registered_method=True)
        self.GetStorageUsage = channel.unary_unary(
                '/fileengine_rpc.FileService/GetStorageUsage',
                request_serializer=fileservice__pb2.StorageUsageRequest.SerializeToString,
                response_deserializer=fileservice__pb2.StorageUsageResponse.FromString,
                _registered_method=True)
        self.PurgeOldVersions = channel.unary_unary(
                '/fileengine_rpc.FileService/PurgeOldVersions',
                request_serializer=fileservice__pb2.PurgeOldVersionsRequest.SerializeToString,
                response_deserializer=fileservice__pb2.PurgeOldVersionsResponse.FromString,
                _registered_method=True)
        self.TriggerSync = channel.unary_unary(
                '/fileengine_rpc.FileService/TriggerSync',
                request_serializer=fileservice__pb2.TriggerSyncRequest.SerializeToString,
                response_deserializer=fileservice__pb2.TriggerSyncResponse.FromString,
                _registered_method=True)


class FileServiceServicer(object):
    """Service definition for the FileEngine virtual filesystem
    """

    def MakeDirectory(self, request, context):
        """Directory operations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveDirectory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListDirectory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListDirectoryWithDeleted(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Touch(self, request, context):
        """File operations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UndeleteFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PutFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Stat(self, request, context):
        """File information
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Exists(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Rename(self, request, context):
        """File manipulation operations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Move(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Copy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListVersions(self, request, context):
        """Version operations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetVersion(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RestoreToVersion(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetMetadata(self, request, context):
        """Metadata operations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMetadata(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAllMetadata(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteMetadata(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMetadataForVersion(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAllMetadataForVersion(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GrantPermission(self, request, context):
        """ACL operations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RevokePermission(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckPermission(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamFileUpload(self, request_iterator, context):
        """Streaming operations for large files
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamFileDownload(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStorageUsage(self, request, context):
        """Administrative operations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PurgeOldVersions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TriggerSync(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FileServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'MakeDirectory': grpc.unary_unary_rpc_method_handler(
                    servicer.MakeDirectory,
                    request_deserializer=fileservice__pb2.MakeDirectoryRequest.FromString,
                    response_serializer=fileservice__pb2.MakeDirectoryResponse.SerializeToString,
            ),
            'RemoveDirectory': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveDirectory,
                    request_deserializer=fileservice__pb2.RemoveDirectoryRequest.FromString,
                    response_serializer=fileservice__pb2.RemoveDirectoryResponse.SerializeToString,
            ),
            'ListDirectory': grpc.unary_unary_rpc_method_handler(
                    servicer.ListDirectory,
                    request_deserializer=fileservice__pb2.ListDirectoryRequest.FromString,
                    response_serializer=fileservice__pb2.ListDirectoryResponse.SerializeToString,
            ),
            'ListDirectoryWithDeleted': grpc.unary_unary_rpc_method_handler(
                    servicer.ListDirectoryWithDeleted,
                    request_deserializer=fileservice__pb2.ListDirectoryWithDeletedRequest.FromString,
                    response_serializer=fileservice__pb2.ListDirectoryWithDeletedResponse.SerializeToString,
            ),
            'Touch': grpc.unary_unary_rpc_method_handler(
                    servicer.Touch,
                    request_deserializer=fileservice__pb2.TouchRequest.FromString,
                    response_serializer=fileservice__pb2.TouchResponse.SerializeToString,
            ),
            'RemoveFile': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveFile,
                    request_deserializer=fileservice__pb2.RemoveFileRequest.FromString,
                    response_serializer=fileservice__pb2.RemoveFileResponse.SerializeToString,
            ),
            'UndeleteFile': grpc.unary_unary_rpc_method_handler(
                    servicer.UndeleteFile,
                    request_deserializer=fileservice__pb2.UndeleteFileRequest.FromString,
                    response_serializer=fileservice__pb2.UndeleteFileResponse.SerializeToString,
            ),
            'PutFile': grpc.unary_unary_rpc_method_handler(
                    servicer.PutFile,
                    request_deserializer=fileservice__pb2.PutFileRequest.FromString,
                    response_serializer=fileservice__pb2.PutFileResponse.SerializeToString,
            ),
            'GetFile': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFile,
                    request_deserializer=fileservice__pb2.GetFileRequest.FromString,
                    response_serializer=fileservice__pb2.GetFileResponse.SerializeToString,
            ),
            'Stat': grpc.unary_unary_rpc_method_handler(
                    servicer.Stat,
                    request_deserializer=fileservice__pb2.StatRequest.FromString,
                    response_serializer=fileservice__pb2.StatResponse.SerializeToString,
            ),
            'Exists': grpc.unary_unary_rpc_method_handler(
                    servicer.Exists,
                    request_deserializer=fileservice__pb2.ExistsRequest.FromString,
                    response_serializer=fileservice__pb2.ExistsResponse.SerializeToString,
            ),
            'Rename': grpc.unary_unary_rpc_method_handler(
                    servicer.Rename,
                    request_deserializer=fileservice__pb2.RenameRequest.FromString,
                    response_serializer=fileservice__pb2.RenameResponse.SerializeToString,
            ),
            'Move': grpc.unary_unary_rpc_method_handler(
                    servicer.Move,
                    request_deserializer=fileservice__pb2.MoveRequest.FromString,
                    response_serializer=fileservice__pb2.MoveResponse.SerializeToString,
            ),
            'Copy': grpc.unary_unary_rpc_method_handler(
                    servicer.Copy,
                    request_deserializer=fileservice__pb2.CopyRequest.FromString,
                    response_serializer=fileservice__pb2.CopyResponse.SerializeToString,
            ),
            'ListVersions': grpc.unary_unary_rpc_method_handler(
                    servicer.ListVersions,
                    request_deserializer=fileservice__pb2.ListVersionsRequest.FromString,
                    response_serializer=fileservice__pb2.ListVersionsResponse.SerializeToString,
            ),
            'GetVersion': grpc.unary_unary_rpc_method_handler(
                    servicer.GetVersion,
                    request_deserializer=fileservice__pb2.GetVersionRequest.FromString,
                    response_serializer=fileservice__pb2.GetVersionResponse.SerializeToString,
            ),
            'RestoreToVersion': grpc.unary_unary_rpc_method_handler(
                    servicer.RestoreToVersion,
                    request_deserializer=fileservice__pb2.RestoreToVersionRequest.FromString,
                    response_serializer=fileservice__pb2.RestoreToVersionResponse.SerializeToString,
            ),
            'SetMetadata': grpc.unary_unary_rpc_method_handler(
                    servicer.SetMetadata,
                    request_deserializer=fileservice__pb2.SetMetadataRequest.FromString,
                    response_serializer=fileservice__pb2.SetMetadataResponse.SerializeToString,
            ),
            'GetMetadata': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMetadata,
                    request_deserializer=fileservice__pb2.GetMetadataRequest.FromString,
                    response_serializer=fileservice__pb2.GetMetadataResponse.SerializeToString,
            ),
            'GetAllMetadata': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAllMetadata,
                    request_deserializer=fileservice__pb2.GetAllMetadataRequest.FromString,
                    response_serializer=fileservice__pb2.GetAllMetadataResponse.SerializeToString,
            ),
            'DeleteMetadata': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteMetadata,
                    request_deserializer=fileservice__pb2.DeleteMetadataRequest.FromString,
                    response_serializer=fileservice__pb2.DeleteMetadataResponse.SerializeToString,
            ),
            'GetMetadataForVersion': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMetadataForVersion,
                    request_deserializer=fileservice__pb2.GetMetadataForVersionRequest.FromString,
                    response_serializer=fileservice__pb2.GetMetadataForVersionResponse.SerializeToString,
            ),
            'GetAllMetadataForVersion': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAllMetadataForVersion,
                    request_deserializer=fileservice__pb2.GetAllMetadataForVersionRequest.FromString,
                    response_serializer=fileservice__pb2.GetAllMetadataForVersionResponse.SerializeToString,
            ),
            'GrantPermission': grpc.unary_unary_rpc_method_handler(
                    servicer.GrantPermission,
                    request_deserializer=fileservice__pb2.GrantPermissionRequest.FromString,
                    response_serializer=fileservice__pb2.GrantPermissionResponse.SerializeToString,
            ),
            'RevokePermission': grpc.unary_unary_rpc_method_handler(
                    servicer.RevokePermission,
                    request_deserializer=fileservice__pb2.RevokePermissionRequest.FromString,
                    response_serializer=fileservice__pb2.RevokePermissionResponse.SerializeToString,
            ),
            'CheckPermission': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckPermission,
                    request_deserializer=fileservice__pb2.CheckPermissionRequest.FromString,
                    response_serializer=fileservice__pb2.CheckPermissionResponse.SerializeToString,
            ),
            'StreamFileUpload': grpc.stream_unary_rpc_method_handler(
                    servicer.StreamFileUpload,
                    request_deserializer=fileservice__pb2.PutFileRequest.FromString,
                    response_serializer=fileservice__pb2.PutFileResponse.SerializeToString,
            ),
            'StreamFileDownload': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamFileDownload,
                    request_deserializer=fileservice__pb2.GetFileRequest.FromString,
                    response_serializer=fileservice__pb2.GetFileResponse.SerializeToString,
            ),
            'GetStorageUsage': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStorageUsage,
                    request_deserializer=fileservice__pb2.StorageUsageRequest.FromString,
                    response_serializer=fileservice__pb2.StorageUsageResponse.SerializeToString,
            ),
            'PurgeOldVersions': grpc.unary_unary_rpc_method_handler(
                    servicer.PurgeOldVersions,
                    request_deserializer=fileservice__pb2.PurgeOldVersionsRequest.FromString,
                    response_serializer=fileservice__pb2.PurgeOldVersionsResponse.SerializeToString,
            ),
            'TriggerSync': grpc.unary_unary_rpc_method_handler(
                    servicer.TriggerSync,
                    request_deserializer=fileservice__pb2.TriggerSyncRequest.FromString,
                    response_serializer=fileservice__pb2.TriggerSyncResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'fileengine_rpc.FileService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('fileengine_rpc.FileService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FileService(object):
    """Service definition for the FileEngine virtual filesystem
    """

    @staticmethod
    def MakeDirectory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fileengine_rpc.FileService/MakeDirectory',
            fileservice__pb2.MakeDirectoryRequest.SerializeToString,
            fileservice__pb2.MakeDirectoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveDirectory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fileengine_rpc.FileService/RemoveDirectory',
            fileservice__pb2.RemoveDirectoryRequest.SerializeToString,
            fileservice__pb2.RemoveDirectoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListDirectory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fileengine_rpc.FileService/ListDirectory',
            fileservice__pb2.ListDirectoryRequest.SerializeToString,
            fileservice__pb2.ListDirectoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListDirectoryWithDeleted(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fileengine_rpc.FileService/ListDirectoryWithDeleted',
            fileservice__pb2.ListDirectoryWithDeletedRequest.SerializeToString,
            fileservice__pb2.ListDirectoryWithDeletedResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Touch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fileengine_rpc.FileService/Touch',
            fileservice__pb2.TouchRequest.SerializeToString,
            fileservice__pb2.TouchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fileengine_rpc.FileService/RemoveFile',
            fileservice__pb2.RemoveFileRequest.SerializeToString,
            fileservice__pb2.RemoveFileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UndeleteFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fileengine_rpc.FileService/UndeleteFile',
            fileservice__pb2.UndeleteFileRequest.SerializeToString,
            fileservice__pb2.UndeleteFileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PutFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fileengine_rpc.FileService/PutFile',
            fileservice__pb2.PutFileRequest.SerializeToString,
            fileservice__pb2.PutFileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fileengine_rpc.FileService/GetFile',
            fileservice__pb2.GetFileRequest.SerializeToString,
            fileservice__pb2.GetFileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Stat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fileengine_rpc.FileService/Stat',
            fileservice__pb2.StatRequest.SerializeToString,
            fileservice__pb2.StatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Exists(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fileengine_rpc.FileService/Exists',
            fileservice__pb2.ExistsRequest.SerializeToString,
            fileservice__pb2.ExistsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Rename(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fileengine_rpc.FileService/Rename',
            fileservice__pb2.RenameRequest.SerializeToString,
            fileservice__pb2.RenameResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Move(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fileengine_rpc.FileService/Move',
            fileservice__pb2.MoveRequest.SerializeToString,
            fileservice__pb2.MoveResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Copy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fileengine_rpc.FileService/Copy',
            fileservice__pb2.CopyRequest.SerializeToString,
            fileservice__pb2.CopyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListVersions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fileengine_rpc.FileService/ListVersions',
            fileservice__pb2.ListVersionsRequest.SerializeToString,
            fileservice__pb2.ListVersionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetVersion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fileengine_rpc.FileService/GetVersion',
            fileservice__pb2.GetVersionRequest.SerializeToString,
            fileservice__pb2.GetVersionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RestoreToVersion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fileengine_rpc.FileService/RestoreToVersion',
            fileservice__pb2.RestoreToVersionRequest.SerializeToString,
            fileservice__pb2.RestoreToVersionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetMetadata(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fileengine_rpc.FileService/SetMetadata',
            fileservice__pb2.SetMetadataRequest.SerializeToString,
            fileservice__pb2.SetMetadataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMetadata(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fileengine_rpc.FileService/GetMetadata',
            fileservice__pb2.GetMetadataRequest.SerializeToString,
            fileservice__pb2.GetMetadataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAllMetadata(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fileengine_rpc.FileService/GetAllMetadata',
            fileservice__pb2.GetAllMetadataRequest.SerializeToString,
            fileservice__pb2.GetAllMetadataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteMetadata(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fileengine_rpc.FileService/DeleteMetadata',
            fileservice__pb2.DeleteMetadataRequest.SerializeToString,
            fileservice__pb2.DeleteMetadataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMetadataForVersion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fileengine_rpc.FileService/GetMetadataForVersion',
            fileservice__pb2.GetMetadataForVersionRequest.SerializeToString,
            fileservice__pb2.GetMetadataForVersionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAllMetadataForVersion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fileengine_rpc.FileService/GetAllMetadataForVersion',
            fileservice__pb2.GetAllMetadataForVersionRequest.SerializeToString,
            fileservice__pb2.GetAllMetadataForVersionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GrantPermission(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fileengine_rpc.FileService/GrantPermission',
            fileservice__pb2.GrantPermissionRequest.SerializeToString,
            fileservice__pb2.GrantPermissionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RevokePermission(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fileengine_rpc.FileService/RevokePermission',
            fileservice__pb2.RevokePermissionRequest.SerializeToString,
            fileservice__pb2.RevokePermissionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CheckPermission(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fileengine_rpc.FileService/CheckPermission',
            fileservice__pb2.CheckPermissionRequest.SerializeToString,
            fileservice__pb2.CheckPermissionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamFileUpload(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/fileengine_rpc.FileService/StreamFileUpload',
            fileservice__pb2.PutFileRequest.SerializeToString,
            fileservice__pb2.PutFileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamFileDownload(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/fileengine_rpc.FileService/StreamFileDownload',
            fileservice__pb2.GetFileRequest.SerializeToString,
            fileservice__pb2.GetFileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStorageUsage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fileengine_rpc.FileService/GetStorageUsage',
            fileservice__pb2.StorageUsageRequest.SerializeToString,
            fileservice__pb2.StorageUsageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PurgeOldVersions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fileengine_rpc.FileService/PurgeOldVersions',
            fileservice__pb2.PurgeOldVersionsRequest.SerializeToString,
            fileservice__pb2.PurgeOldVersionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TriggerSync(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fileengine_rpc.FileService/TriggerSync',
            fileservice__pb2.TriggerSyncRequest.SerializeToString,
            fileservice__pb2.TriggerSyncResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
